# 
#-----------------------------------------------------
#
# Rate for how often a bee will have an LGBT+ coat!
#
#Range: 0.0 ~ 1.0
"lgbt+ bee rates" = 0.02
# 
#-----------------------------------------------------
#
# Enable replacing the bee renderer for LGBT+ skins.
# Set this to false if the render is messing with other mod's bee renderers.
#
"Enable lgbt+ bee renderer" = true
# 
#-----------------------------------------------------
#
# If on, Flight of the Bumblebee by Rimsky Korsakov will play when you have Wrath of the Hive effect on.
#
playWrathOfHiveEffectMusic = true

